### ISSUE TITLE
Create a Post (2)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-client-nunchuk-falcons#10]
Given a user selects the "New Post" link in the navbar and are directed to the new post form
When they fill out the form correctly and submit
Then the post should be added and approved
And they should be directed to that post's detail page

[Server Side](https://github.com/NSS-Day-Cohort-58/rare-python-server-nunchuk-falcons/issues/7)
[Client Side](https://github.com/NSS-Day-Cohort-58/rare-client-nunchuk-falcons/issues/35)

**Comment by codinglumos** [comment]
2

**Comment by NathanAMalone** [comment]
2

**Comment by carlydopps** [comment]
2 or 3 if we need to include the approval process
