### ISSUE TITLE
View Current User's Posts (2)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-client-nunchuk-falcons#11]
Given the logged in user wants to view a list of posts they have created
When they select the "My Posts" link from the navbar
Then they should be taken to `/my-posts` that only shows posts they have authored
And there should be (non-functional) buttons to edit or delete each post

**Comment by codinglumos** [comment]
1/2

**Comment by NathanAMalone** [comment]
2

**Comment by carlydopps** [comment]
2
