### ISSUE TITLE
Edit a post (2)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-client-nunchuk-falcons#12]
Given the logged in user is on the `/my-posts` page
When they select a post's edit button
Then they should be directed to an edit form with that posts's content filled in
And when the form is updated and submitted
Then they should be directed to that post's detail page with the updated information

Related Tickets:
[Client](https://github.com/NSS-Day-Cohort-58/rare-client-nunchuk-falcons/issues/47)
[Server](https://github.com/NSS-Day-Cohort-58/rare-client-nunchuk-falcons/issues/45)

**Comment by codinglumos** [comment]
2

**Comment by NathanAMalone** [comment]
2

**Comment by carlydopps** [comment]
3
