### ISSUE TITLE
View Category List (2)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-client-nunchuk-falcons#6]
Given a user selects the "Category Management" from the navbar
When they are directed to `/categories`
Then they should see a list of all categories
And categories should be ordered alphabetically
And each category should have an edit and delete button (functionality for buttons come later) 

[Server Side](https://github.com/NSS-Day-Cohort-58/rare-python-server-nunchuk-falcons/issues/3)
[Client Side](https://github.com/NSS-Day-Cohort-58/rare-client-nunchuk-falcons/issues/31)

**Comment by codinglumos** [comment]
Faith - 2/3

**Comment by JayMy45** [comment]
Sprint Velocity
Jeremy - 2

**Comment by carlydopps** [comment]
2

**Comment by NathanAMalone** [comment]
2
