### ISSUE TITLE
View Tag List (2)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-client-nunchuk-falcons#7]
Given a user selects the "Tag Management" from the navbar
When they are directed to `/tags`
Then they should see a list of all tags
And tags should be ordered alphabetically
And each tag should have an edit and delete button (functionality for buttons come later) 

[Server Side](https://github.com/NSS-Day-Cohort-58/rare-python-server-nunchuk-falcons/issues/4)
[Client Side](https://github.com/NSS-Day-Cohort-58/rare-client-nunchuk-falcons/issues/32)

**Comment by codinglumos** [comment]
2/3

**Comment by JayMy45** [comment]
Sprint Velocity
Jeremy - 2/3

**Comment by NathanAMalone** [comment]
2

**Comment by carlydopps** [comment]
2
