### ISSUE TITLE
Create A Category (3)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-client-nunchuk-falcons#8]
Given a user is on the category list page, there should be a create form on the right side of the page
When they fill out the form and submit
Then the category should be added
And the category list should update

[Server Side](https://github.com/NSS-Day-Cohort-58/rare-python-server-nunchuk-falcons/issues/5)
[Client Side](https://github.com/NSS-Day-Cohort-58/rare-client-nunchuk-falcons/issues/36)

**Comment by carlydopps** [comment]
3

**Comment by NathanAMalone** [comment]
3
