### ISSUE TITLE
Create a Tag (2)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-client-nunchuk-falcons#9]
Given a user is on the tag list page, there should be a create form on the right side of the page
When they fill out the form and submit
Then the tag should be added
And the tag list should update

[Server Side](https://github.com/NSS-Day-Cohort-58/rare-python-server-nunchuk-falcons/issues/6)
[Client Side](https://github.com/NSS-Day-Cohort-58/rare-client-nunchuk-falcons/issues/34)

**Comment by codinglumos** [comment]
2

**Comment by carlydopps** [comment]
2

**Comment by NathanAMalone** [comment]
2
